### PR TITLE
Events as records, approach 3.

### PR DESCRIPTION
**Pull request by cknitt**
I took @sgny's #694 and rewrote it to get rid of type parameters and to be more similar to the pattern I used for native elements and their methods.

For the moment, I still kept the accessor functions for nullable fields, but I am thinking of removing them.

This compiles, but is otherwise untested.

### CODE REVIEW

**Comment by sgny** [comment]
I had already [tried](https://github.com/reason-react-native/reason-react-native/blob/event_functors/src/apis/Event.re) a similar approach except for defining

```reason
module ErrorEvent =
  Event.SyntheticEvent({
    type payload = {error: string};
  });
```
instead of
```reason
module ErrorEvent = {
  type payload = {error: string};

  include Event.SyntheticEvent({
    type _payload = payload;
  });
};
```
and kept getting errors trying to access fields, both with local opens and type annotations. However, as I kept getting errors even with fields such as `nativeEvent`, I didn't suspect inline definition of `payload`.

Anyway, I've tried your version and it works. Further, it can be broken with inline definition.  I switched to the simplified version and as that seems to work even with inline definition, perhaps my definition is an edge case that is slightly buggy.

**Comment by sgny** [comment]
Checked just now,
```reason
module ErrorPayload = {
  type payload = {error: string};
};
module ErrorEvent =
  Event.SyntheticEvent(ErrorPayload);
```
works, so the issue I had really is that the module was defined inline.

**Comment by sgny** [comment]
This doesn't seem to be a BuckleScript issue. I tested on OCaml and when `module Layout` is not defined, the signature of `LayoutEvent` has `t` as an opaque type.

However, that's not the case when the module passed as argument to `SyntheticEvent` is `{type t = string;}`.

**Comment by jfrolich** [comment]
> I had already [tried](https://github.com/reason-react-native/reason-react-native/blob/event_functors/src/apis/Event.re) a similar approach except for defining
> 
> ```reason
> module ErrorEvent =
>   Event.SyntheticEvent({
>     type payload = {error: string};
>   });
> ```
> 
> instead of
> 
> ```reason
> module ErrorEvent = {
>   type payload = {error: string};
> 
>   include Event.SyntheticEvent({
>     type _payload = payload;
>   });
> };
> ```
> 
> and kept getting errors trying to access fields, both with local opens and type annotations. However, as I kept getting errors even with fields such as `nativeEvent`, I didn't suspect inline definition of `payload`.
> 
> Anyway, I've tried your version and it works. Further, it can be broken with inline definition so there might be a bug with the compiler for this edge case, either it should work or it should lead to an error referring to the inline definition.

I just read it, did you try the following:

> ```reason
> module ErrorEvent = {
>   type payload = {error: string};
> 
>   include Event.SyntheticEvent({
>     type payload;
>   } with type payload := payload;;
> };
> ```

This is the syntax to redefine types in an include.

**Comment by sgny** [comment]
> > I had already [tried](https://github.com/reason-react-native/reason-react-native/blob/event_functors/src/apis/Event.re) a similar approach except for defining
> > ```reason
> > module ErrorEvent =
> >   Event.SyntheticEvent({
> >     type payload = {error: string};
> >   });
> > ```
> > 
> > 
> > instead of
> > ```reason
> > module ErrorEvent = {
> >   type payload = {error: string};
> > 
> >   include Event.SyntheticEvent({
> >     type _payload = payload;
> >   });
> > };
> > ```
> > 
> > 
> > and kept getting errors trying to access fields, both with local opens and type annotations. However, as I kept getting errors even with fields such as `nativeEvent`, I didn't suspect inline definition of `payload`.
> > Anyway, I've tried your version and it works. Further, it can be broken with inline definition so there might be a bug with the compiler for this edge case, either it should work or it should lead to an error referring to the inline definition.
> 
> I just read it, did you try the following:
> 
> > ```reason
> > module ErrorEvent = {
> >   type payload = {error: string};
> > 
> >   include Event.SyntheticEvent({
> >     type payload;
> >   }) with type payload := payload;
> > };
> > ```
> 
> This is the syntax to redefine types in an include.
> 
> Possibly we can even remove the need for it to be a functor (why is it a functor?)
> 
> This would possibly enable the following:
> 
> > ```reason
> > module ErrorEvent = {
> >   type payload = {error: string};
> > 
> >   include Event.SyntheticEvent with type payload := payload;
> > };
> > ```
> 
> Much simpler 😄

That syntax doesn't work for me on 7.3.2 or 8.0.0. Something like 
```reason
module SyntheticEvent = {
	type payload;

  type t = {
    bubbles: Js.Nullable.t(bool),
    cancelable: Js.Nullable.t(bool),
    currentTarget: float,
    defaultPrevented: Js.Nullable.t(bool),
    dispatchConfig: registrationName,
    eventPhase: Js.Nullable.t(float),
    isTrusted: Js.Nullable.t(bool),
    target: Js.Nullable.t(float),
    timeStamp: float,
    [@bs.as "type"]
    _type: Js.Nullable.t(string),
  };

  include EventMethods({
    type event = t;
  });
};

module ErrorEvent = {
	type payload = {error: string};

	include (SyntheticEvent:  (module type of SyntheticEvent) with type payload := payload);
};
```
works only when `t` does not depend on `payload` as above. Once the `nativeEvent` key is added, it appears we have to override `t` as well.

Sorry for dropping off the conversation, I've been swamped with a work project in the past weeks, but now I'm free(r) now that I've submitted my part yesterday.

**Comment by jfrolich** [comment]
Sorry you probably need to do this in the module type definition instead of the module implementation.

**Comment by jfrolich** [comment]
```reason
module type ErrorEvent {
  type payload = {error: string};

  include Event.SyntheticEvent with type payload := payload;
};
```

**Comment by sgny** [comment]
> ```reason
> module type ErrorEvent {
>   type payload = {error: string};
> 
>   include Event.SyntheticEvent with type payload := payload;
> };
> ```

I've tried similar ideas the other day, but I couldn't exactly figure out a solution. I believe we would need to either define a module of that type or a functor that outputs that type to actually make use of it. Further, it appears any of the additional definitions can't reference that signature so we would have to repeat definitions. Have you been able to make this work?

**Comment by jfrolich** [comment]
How about this:

```reason

module type SyntheticEvent_intf = {
  type payload;
  type otherType = int;
};

module SyntheticEvent: SyntheticEvent_intf = {
  type payload;
  type otherType = int;
};

module ErrorEvent = {
  type payload = {error: string};

  include (SyntheticEvent: { 
    include SyntheticEvent_intf with type payload := payload 
  });
  let payload = {error: "error"}; 
};

Js.log(ErrorEvent.payload.error);
```


See the following link for an example: https://reasonml.github.io/en/try?rrjsx=true&reason=LYewJgrgNgpgBAFwJ4Ad4GUkDsEAsYICWAxgKIBuMOA+oTgGZwC8cA3gFByKrwoCGSKCD5gA3J25o4IPDABOAFR7M4dBOIC+49qEiw4mHPiJlKOAFwHsskxSoJaDFRy7Ip-QcLES38GfkVlFjVNbV1oeFI5ORA5OxxnH2UPIRFneRi5SwBnBDk6AHMtdgk6YigIMHgACkMbEniES1Y4CS4yiqqrIwIGswc1RgB3QjxJXgFUsDhzFhSvVq4NAEpxLlgEOHm0llYM2MsAIn25Q61W4vYAKWyAOiEC6qjMxtvtsFuT1aA

**Comment by sgny** [comment]
I don't think that works when type t depends on payload. See this [version](https://reasonml.github.io/en/try?rrjsx=true&reason=LYewJgrgNgpgBAFwJ4Ad4GUkDsEAsYICWAxgKIBuMOA+oTgGZwC8cA3gFByKrwoCGSKCD5gA3J25o4IPDABOAFR7M4dBOIC+49qEiw4mHPiJlKOAFwHsskxSoJaDFRy7Ip-QcLES38GfkVlFjVNbV1oeFI5ORA5OxxnH2UPIRFqZ3kYuUsAZwQ5OgBzLXYJOmIoCDB4AApDGxJ4hEtWOAkucsrqqyMCRrMHNUYAd0I8SV4BVLA4cxYUr3SJDQBKbRL2WAQ4BZFLKKymgDpdmZZWTNjLACJLuWutNvYAKRyjoUKa06O7taA) where

```reason
  include (SyntheticEvent: { 
    include SyntheticEvent_intf with type payload := payload_ 
  });
```

should bring the definition of `payload` into the module, but that doesn't seem to be the case. It's not an export issue either, even if you move the instance into the module, it still doesn't work as the constructor cannot be found.

**Comment by jfrolich** [comment]
There was a typo in your example, here a fixed [version](https://reasonml.github.io/en/try?rrjsx=true&reason=LYewJgrgNgpgBAFwJ4Ad4GUkDsEAsYICWAxgKIBuMOA+oTgGZwC8cA3gFByKrwoCGSKCD5gA3J25o4IPDABOAFR7M4dBOIC+49qEiw4mHPiJlKOAFwHsskxSoJaDFRy7Ip-QcLES38GfkVlFjVNbV1oeFI5ORA5OxxnH2UPIRFqZ3kYuUsAZwQ5OgBzLXYJOmIoCDB4AApDGxJ4hEtWOAkucsrqqyMCRrMHNUYAd0I8SV4BVLA4cxYUr3SJDQBKbRL2WAQ4BZFLKKymgDpdsHSWVkzYywAiK7kbrTb2ACkco6FCmtOj+7WgA)

**Comment by jfrolich** [comment]
I don't think that works when type t depends on payload, the interface has to specify t as well, as far as I have found.

Why don't you think it doesn't work? Yes type t needs to be in the interface (if you don't want to specify the module type you can do `module type of Xxx`, but I think it's good practice to specify module types.

**Comment by sgny** [comment]
> There was a typo in your example, here a fixed [version](https://reasonml.github.io/en/try?rrjsx=true&reason=LYewJgrgNgpgBAFwJ4Ad4GUkDsEAsYICWAxgKIBuMOA+oTgGZwC8cA3gFByKrwoCGSKCD5gA3J25o4IPDABOAFR7M4dBOIC+49qEiw4mHPiJlKOAFwHsskxSoJaDFRy7Ip-QcLES38GfkVlFjVNbV1oeFI5ORA5OxxnH2UPIRFqZ3kYuUsAZwQ5OgBzLXYJOmIoCDB4AApDGxJ4hEtWOAkucsrqqyMCRrMHNUYAd0I8SV4BVLA4cxYUr3SJDQBKbRL2WAQ4BZFLKKymgDpdsHSWVkzYywAiK7kbrTb2ACkco6FCmtOj+7WgA)

That was my point actually. You get the type `payload_` but not `payload` that should be brought into scope with the `include` statement.

**Comment by jfrolich** [comment]
> That was my point actually. You get the type `payload_` but not `payload` that should be brought into scope with the `include` statement.

Because the `payload` has been replaced with `payload_`.

**Comment by sgny** [comment]
> > That was my point actually. You get the type `payload_` but not `payload` that should be brought into scope with the `include` statement.
> 
> Because the `payload` has been replaced with `payload_`.

I had understood that syntax as replacing the abstract type `payload` with the type `payload`  as defined in `ErrorEvent`, but that was incorrect I see that `othertype` is included in `ErrorEvent`.

Assuming `otherType` is a record where the key `payload` is of type `payload`, we can handle that as in this [version](https://reasonml.github.io/en/try?rrjsx=true&reason=LYewJgrgNgpgBAFwJ4Ad4GUkDsEAsYICWAxgKIBuMOA+oTgGZwC8cA3gFByKrwoDcnbmjgg8MAE4AVHszYoAhkigh5YAFxwUAXwE727UJFhxMOfETKUcG02IsUqCWg1kcuyYf0Ef4o-FJkWVgUlFXVNPT0DcGh4UnFxEHEHHFdvGRDlVVcJRPENAGcEcToAcz13GT8JaWEgzLCorjpiKAgweAAKW3MSFIQNVjhBZqxW9oxsOz6rJzoERgB3QjwhXjg1Fgbs+SwwNZExAOFNw-9amEEtAEpdAXZYBDh5DXi8-oA6auP4esUs8KsXJJDQAIiKJSwpVBWii7CAA), but that seems to require defining `t` for each type of event. As in the example, `otherType` can't be defined inline and now that I understand what the syntax actually does, that's hardly suprising - you cannot have an unnamed type.

However if we already have the definitions of `payload` and `t` in the module, what benefit do we get from the include statement? If the modules had further definitions, that did not depend on `payload` or `t`, sure we can simply replace those and proceed. However, all methods in `EventMethods` also depend on `t`, so we'd have to define them as well.

**Comment by jfrolich** [comment]
> > > That was my point actually. You get the type `payload_` but not `payload` that should be brought into scope with the `include` statement.
> > 
> > 
> > Because the `payload` has been replaced with `payload_`.
> 
> I had understood that syntax as replacing the abstract type `payload` with the type `payload` as defined in `ErrorEvent`, but that was incorrect I see that `othertype` is included in `ErrorEvent`.
> 
> Assuming `otherType` is a record where the key `payload` is of type `payload`, we can handle that as in this [version](https://reasonml.github.io/en/try?rrjsx=true&reason=LYewJgrgNgpgBAFwJ4Ad4GUkDsEAsYICWAxgKIBuMOA+oTgGZwC8cA3gFByKrwoDcnbmjgg8MAE4AVHszYoAhkigh5YAFxwUAXwE727UJFhxMOfETKUcG02IsUqCWg1kcuyYf0Ef4o-FJkWVgUlFXVNPT0DcGh4UnFxEHEHHFdvGRDlVVcJRPENAGcEcToAcz13GT8JaWEgzLCorjpiKAgweAAKW3MSFIQNVjhBZqxW9oxsOz6rJzoERgB3QjwhXjg1Fgbs+SwwNZExAOFNw-9amEEtAEpdAXZYBDh5DXi8-oA6auP4esUs8KsXJJDQAIiKJSwpVBWii7CAA), but that seems to require defining `t` for each type of event. As in the example, `otherType` can't be defined inline and now that I understand what the syntax actually does, that's hardly suprising - you cannot have an unnamed type.
> 
> However if we already have the definitions of `payload` and `t` in the module, what benefit do we get from the include statement? If the modules had further definitions, that did not depend on `payload` or `t`, sure we can simply replace those and proceed. However, all methods in `EventMethods` also depend on `t`, so we'd have to define them as well.

If you don't want to redefine `t` you can do that with a functor I think.

**Comment by jfrolich** [comment]
Ok how about this:

```reason
module type SyntheticEvent_intf = {
  type payload;
};

module MakeSyntheticEvent = (M: SyntheticEvent_intf) => {
  type t = {embeddedPayload: M.payload};
};

module ErrorPayload = {
  type payload = {error: string};
};

module ErrorEvent = {
  include MakeSyntheticEvent(ErrorPayload);
  let payload = {
    embeddedPayload: {
      error: "error",
    },
  };
};

Js.log(ErrorEvent.payload.embeddedPayload.error);
```

Working version [here](https://reasonml.github.io/en/try?rrjsx=true&reason=LYewJgrgNgpgBAFwJ4Ad4GUkDsEAsYICWAxgKIBuMOA+oTgGZwC8cA3gFByKrwoCGSKCD5gA3OwC+49qEiw4AWT4BrGJhz4iZSjmZwAFAoBccdXgIkKVBLQYBKZgD42nbmkR7WMYACMYYMH8ABQEhERMFADp+QWEwKUlpWWh4UgAnNJA0kNiRT1dkdxiwsE8YDKyTAGcENLoAcwSEmXAUuHTMtKtdFg4uOmIoCEDFFTVscy1uhH0OrJySu3EuWAQ4Yrj8ri5vPwDg0LiTPu2dirSTACJyzsuAGlcuCQen8WaAKSrIoXrZ8+noocRJFdv5AmAFnEQeclkA)

**Comment by jfrolich** [comment]
I probably miss context here by why not just parameterize type `t`?

**Comment by jfrolich** [comment]
> Checked just now,
> 
> ```reason
> module ErrorPayload = {
>   type payload = {error: string};
> };
> module ErrorEvent =
>   Event.SyntheticEvent(ErrorPayload);
> ```
> 
> works, so the issue I had really is that the module was defined inline.

My suggestion is very similar to this. What is the problem with this?

**Comment by sgny** [comment]
> > Checked just now,
> > ```reason
> > module ErrorPayload = {
> >   type payload = {error: string};
> > };
> > module ErrorEvent =
> >   Event.SyntheticEvent(ErrorPayload);
> > ```
> > 
> > 
> > works, so the issue I had really is that the module was defined inline.
> 
> My suggestion is very similar to this. What is the problem with this?

What I tried at first was
```reason
module ErrorEvent =
  Event.SyntheticEvent( type payload = {error: string};);
```

which seems reasonable enough. Doesn't throw any compilation errors anyway. However, the resulting module signature has an abstract `t`, so none of the fields are accessible. In contrast, if you try something like 
```reason
module ErrorEvent =
  Event.SyntheticEvent( type payload = string;);
```
you'd have the type defined as expected in the module signature. Since I hadn't identifed the difference, I ended up with the other PR.

**Comment by MoOx** [comment]
Maybe we should focus on UX instead of implementation to help us decide what is the best?
Is there any difference between the 3 pending implantation in term of developer experience?

**Comment by sgny** [comment]
> Maybe we should focus on UX instead of implementation to help us decide what is the best?
> Is there any difference between the 3 pending implantation in term of developer experience?

I've been sitting out on the UX question, but #2 and #3 are identical in use. Scope to access fields and use methods will be the actual event submodules, such as `PressEvent`, etc. This could allow a single local open, such as `PressEvent.(....)`

With #1, the methods are defined in `Event` and not included in each submodule (though it could be revised), so the scope for methods is `Event` but to access fields, one would need `PressEvent`.

I also think we have stalled a new release for too long, so we should quickly decide on this.

**Comment by jfrolich** [comment]
AFAIK 3 is just an improved 2 (better implementation). And 2-3 are better in UX than 1 because it allows a single local open. Or did I overlook something?

**Comment by MoOx** [comment]
Ok thanks for the explanation.
We need to move on & work on 0.63 :)

Are you ok to merge this PR & close the 2 first implementations? @sgny @jfrolich 
@sgny I know you worked hard on this & don't want you to feel that you don't get credit for this as this PR is by @cknitt

**Comment by sgny** [comment]
> Ok thanks for the explanation.
> We need to move on & work on 0.63 :)
> 
> Are you ok to merge this PR & close the 2 first implementations? @sgny @jfrolich
> @sgny I know you worked hard on this & don't want you to feel that you don't get credit for this as this PR is by @cknitt

No worries, I'm fine with it.

**Comment by MoOx** [comment]
Ok, merging & preparing release!!!

**Pull request merged**
