### PR TITLE
Revise definition of ref for Animated components

### PR DESCRIPTION
**Pull request by sgny**
Here's one way to address #643. JS output is unchanged, but the ref is wrapped and has to be accessed with an appropriate function.

### CODE REVIEW

**Comment by sgny** [comment]
I removed `Obj.magic` where it wasn't needed, even if it would cause no additional cost.

**Comment by sgny** [comment]
We could also define
```reason
type animatedRef('ref) = {
  .
  "_component": 'ref
};
```
to access the `_component` prop, but I understand that use has been deprecated in favor of the `getNode` method.

**Comment by MoOx** [comment]
Nice changes! Not sure like you said that relying on `_component` is necessary, especially if we already offers an "official" way to do the same

**Comment by cknitt** [comment]
Looks nice! Quite a lot of effort though for a problem that will be gone with 0.62 anyway. So we will then roll back these changes?

Why are there still some `Obj.magic` in some places? Are they required for some components but not for others?

**Comment by sgny** [comment]
@MoOx I haven't checked if `_component` key still exists, but I don't think it's necessary as you said.

@cknitt 
I was hoping this could be handled while including module * in Animated.*, but I don't think that's possible yet with BuckleScript, so I took this approach.

We should roll these changes back because at some point `getNode` will be removed and code using it will cause errors. We could redefine `getNode` to wrap the external definition with a version check to avoid throwing deprecation warnings or add another function to simply cast `animatedRef('ref)` to `'ref`.

As `FlatList` and `SectionList` take parametrised types for some props, the compiler complains without `Obj.magic`. We could include `type item` alongside `type t` in the signature for modules passed to `FlatList.Make` or `SectionList.Make` but that would be more cumbersome for users.

**Comment by sgny** [comment]
@MoOx @cknitt 
The last piece is a way to pass an `animatedRef`, so we should also add something like
```reason
external createAnimatedRef: React.Ref.t(Js.nullable('ref)) =>
   animatedRef(React.Ref.t(Js.nullable('ref))) = "%identity";
```
Perhaps it makes sense to be more precise with `getNode` as well, as below:
```reason
[@bs.send] external getNode: (animatedRef(React.Ref.t(Js.nullable('ref))), unit) =>
   React.Ref.t(Js.nullable('ref)) = "getNode";
```
Any ideas?

**Comment by sgny** [comment]
@MoOx @cknitt 

I figured it would be easier to simply type cast some `ref` with such a function as above, but we could alternatively define
```reason
[@bs.module "react"] external createAnimatedRef: unit => animatedRef(Ref.t(Js.nullable('a))) = "createRef";
[@bs.module "react"] external useAnimatedRef: 'value => animatedRef(Ref.t('value)) = "useRef";
```
or even add the below to `Animated`

```reason
module Ref = {
  [@bs.module "react"] external createRef: unit => animatedRef(Ref.t(Js.nullable('a))) = "createRef";
  [@bs.module "react"] external useRef: 'value => animatedRef(Ref.t('value)) = "useRef";
};
```
to avoid namespace conflicts for those who prefer to `open` various modules.

**Comment by MoOx** [comment]
@sgny I think we should use the thing that would be more intuitive for end user. I have the feeling that the solution that rely on `getNode` definition is what would make it transparent.

**Comment by sgny** [comment]
> ```reason
> [@bs.send] external getNode: (animatedRef(React.Ref.t(Js.nullable('ref))), unit) =>
>    React.Ref.t(Js.nullable('ref)) = "getNode";
> ```

@MoOx I felt this would be easier to understand as well. So basically users have to use the additional methods `createAnimatedRef` and `getNode` to, respectively, pass and access `ref` to `Animated.*` components. I made the signature for `getNode` more explicit (as above) with this latest commit.

**Comment by MoOx** [comment]
That's quite a big change in here. Do we really want this? 
We could also get it and revert it (to simplify codebase) as soon as we tackle RN 0.62?

**Comment by sgny** [comment]
I held off a bit to get other opinions, but this can be undone with a simple `git revert`.

**Comment by sgny** [comment]
@MoOx @cknitt 

It will be a while until 0.62 is out and stable, should we not have this interim fix until then?

**Comment by MoOx** [comment]
0.62 is out, do we want this? :D

**Comment by MoOx** [comment]
I guess not :D

**Pull request closed without merging**
